sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
after_success:
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -DskipTests --settings etc/deploy-settings.xml"
  - mvn verify coveralls:report -Prun-coverage
env:
  global:
    - secure: cttGV5bt0VuZZXHK0yo9rfszAjX67+pcRKMBjGuFEdr3v8uD55ho2qrXAtKEbG5x/g1atBXKD3HhBzK5Mb00XDkF93TQdX9veO6619xcVqQ7LdzPDIbbpX7lrS7vIaUaM77+hCtHFEKZs6+DVyeL93z0Vy7GiIAnRAnGomlmAwc=
    - secure: bjSYB4bs3FXRt9kPkPE3Qex00rckmnrKc1SoNiDXJ9ZHVjGRl3SXjcAUDQiTvmfliuUBMSRryCpjR4xqUywICEwD8tg9ubW7EbI8X12yxtGszJCoGQYTSlVc/bVgM+qaT/KxLvoCI3PTsPgEI/DsSIjmM4uVqzStgcgb02qZWE8=
